### ISSUE TITLE
[Anon] Bug report: A_Song_Of_Ice_and_Fire_Miniatures_Game.gstz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/song-of-ice-and-fire#2]
**File:** A_Song_Of_Ice_and_Fire_Miniatures_Game.gstz

**BattleScribe version:** 2.01.21

**Platform:** Android

**Dropbox:** No

**Description:** Nearly every unit for both houses has incorrect point costs associated with them, especially the Non-Combat units. I don't have the time to list every single one on my phone.

**Comment by Aussiejed** [comment]
Files updated.
