### ISSUE TITLE
[Join Request]

### ISSUE THREAD

**Issue by Aussiejed** [BSData/song-of-ice-and-fire#3]
I notice the information is out of date, I'd like to Join so I may keep them updated.

I've not done any contributions before on Github however have been a member for some time AND have been playing ASOIAF:TMG since the Kickstarter got delivered to me. :)

**Comment by amis92** [comment]
Hello, @Aussiejed. Please accept the invitation in the email or on the [repo page](https://github.com/BSData/song-of-ice-and-fire/invitations). Welcome aboard!

Don't forget to read through [Wiki pages](https://github.com/BSData/bsdata/wiki), there are some useful guides, especially [Developer Guide](https://github.com/BSData/bsdata/wiki/Developer-Guide).

Cheers!
