### ISSUE TITLE
[Anon] Bug report: Mercenaries.catz

### ISSUE THREAD

**Issue by BSDataAnon** [BSData/song-of-ice-and-fire#4]
**File:** Mercenaries.catz

**BattleScribe version:** 2.01.19

**Platform:** iPhone / iPod / iPad

**Dropbox:** No

**Description:** The « Unit Attachment » section is missing its Roose Bolton selection. Not only is he a 
« Commander » selection, he should be avaible as a 3pts unit attachment

**Comment by Aussiejed** [comment]
Fixed in latest release.
